ppa/archive/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, re_path

from ppa.archive import views

app_name = "ppa.archive"

urlpatterns = [
    path(
        "add-to-collection/",
        staff_member_required(views.AddToCollection.as_view()),
        name="add-to-collection",
    ),
    path(
        "opensearch-description/",
        views.OpenSearchDescriptionView.as_view(),
        name="opensearch-description",
    ),
    re_path(
        r"^record/(?P<record_id>\d+)/",
        views.DigitizedWorkByRecordId.as_view(),
        name="record-id",
    ),
    # excerpt original page may be numeric or alpha (e.g., roman numerals)
    re_path(
        r"^(?P<source_id>[^-]+)-p(?P<start_page>[\da-zA-Z]+)/",
        views.DigitizedWorkDetailView.as_view(),
        name="detail",
    ),
    re_path(
        r"^(?P<source_id>[^-]+)/",
        views.DigitizedWorkDetailView.as_view(),
        name="detail",
    ),
    path("", views.DigitizedWorkListView.as_view(), name="list"),
]

ppa/urls.py
"""PPA URL Configuration

"""
from django.conf import settings
from django.conf.urls.static import serve
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView, TemplateView
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps import Sitemap
from wagtail.contrib.sitemaps import views as sitemap_views
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from ppa.archive.sitemaps import ArchiveViewsSitemap, DigitizedWorkSitemap
from ppa.unapi.views import UnAPIView

# sitemap configuration for sections of the site
sitemaps = {
    "pages": Sitemap,  # wagtail content pages
    "archive": ArchiveViewsSitemap,
    "digitizedworks": DigitizedWorkSitemap,
}


urlpatterns = [
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    re_path(
        r"^favicon\.ico$",
        RedirectView.as_view(url="/static/favicon.ico", permanent=True),
    ),
    path("admin/", admin.site.urls),
    # pucas urls for CAS login
    path("accounts/", include("pucas.cas_urls")),
    path("archive/", include("ppa.archive.urls", namespace="archive")),
    # unapi service endpoint for Zotero
    path("unapi/", UnAPIView.as_view(), name="unapi"),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # sitemaps
    re_path(
        r"^sitemap\.xml$",
        sitemap_views.index,
        {"sitemaps": sitemaps},
        name="sitemap-index",
    ),
    re_path(
        r"^sitemap-(?P<section>.+)\.xml$",
        sitemap_views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", include(wagtail_urls)),
]

# serve media content for development
if settings.DEBUG:
    urlpatterns = [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    ] + urlpatterns

    try:
        # include debug toolbar when available
        import debug_toolbar

        urlpatterns = [
            # include debug toolbar urls first to avoid getting caught by other urls
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

ppa/archive/views.py
import logging

import requests
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import MultipleObjectsReturned, ValidationError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import (
    Http404,
    HttpResponsePermanentRedirect,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import DetailView, ListView
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.edit import FormView
from parasolr.django.views import SolrLastModifiedMixin

from ppa.archive.forms import (
    AddToCollectionForm,
    ImportForm,
    SearchForm,
    SearchWithinWorkForm,
)
from ppa.archive.import_util import GaleImporter, HathiImporter
from ppa.archive.models import NO_COLLECTION_LABEL, DigitizedWork, SourceNote
from ppa.archive.solr import ArchiveSearchQuerySet, PageSearchQuerySet
from ppa.common.views import AjaxTemplateMixin

logger = logging.getLogger(__name__)


class GracefulPaginator(Paginator):
    """Paginator override to gracefully handle out-of-range errors.
    Adapted from https://forum.djangoproject.com/t/23037"""

    def page(self, number):
        """Get the page by the supplied number. Reset to 1 if the supplied page is out of
        range."""
        try:
            number = self.validate_number(number)
        except (PageNotAnInteger, EmptyPage):
            number = 1
        return super().page(number)


class DigitizedWorkListView(AjaxTemplateMixin, SolrLastModifiedMixin, ListView):
    """Search and browse digitized works.  Based on Solr index
    of works and pages."""

    model = DigitizedWork
    template_name = "archive/digitizedwork_list.html"
    ajax_template_name = "archive/snippets/results_list.html"
    form_class = SearchForm
    paginate_by = 50
    paginator_class = GracefulPaginator
    #: title for metadata / preview
    meta_title = "Princeton Prosody Archive"
    #: page description for metadata/preview
    meta_description = """The Princeton Prosody Archive is a full-text
    searchable database of thousands of historical documents about the
    study of language and the study of poetry."""

    # keyword query; assume no search terms unless set
    query = None

    def get(self, *args, **kwargs):
        # a bug used to allow aggregation of multiple cluster params,
        # which is not supported; if detected, redirect to archive search
        cluster_param = self.request.GET.getlist("cluster")
        if cluster_param and len(cluster_param) > 1:
            response = HttpResponsePermanentRedirect(reverse("archive:list"))
            response.status_code = 303  # See other
            return response

        # otherwise, process response normally
        return super(DigitizedWorkListView, self).get(*args, **kwargs)

    def paginate_queryset(self, queryset, page_size):
        """Graceful paginate_queryset override to handle non-numeric inputs.
        Adapted from https://stackoverflow.com/a/61214021/394067"""
        try:
            return super().paginate_queryset(queryset, page_size)
        except Http404:
            # handle a 404, e.g. a non-numeric page number was entered
            paginator = self.get_paginator(
                queryset,
                page_size,
                orphans=self.get_paginate_orphans(),
                allow_empty_first_page=self.get_allow_empty(),
            )
            page = paginator.page(1)
            return (paginator, page, page.object_list, page.has_other_pages())

    def get_queryset(self, **kwargs):
        form_opts = self.request.GET.copy()
        # if relevance sort is requested but there is no keyword search
        # term present, clear it out and fallback to default sort
        if not self.form_class().has_keyword_query(form_opts):
            if "sort" in form_opts and form_opts["sort"] == "relevance":
                del form_opts["sort"]

        searchform_defaults = self.form_class.defaults()

        for key, val in searchform_defaults.items():
            # set as list to avoid nested lists
            # follows solution using in derrida-django for InstanceListView
            if isinstance(val, list):
                form_opts.setlistdefault(key, val)
            else:
                form_opts.setdefault(key, val)

        # NOTE: Default sort for keyword search should be relevance but
        # currently no way to distinguish default sort from user selected
        self.form = self.form_class(form_opts)

        # if the form is not valid, return an empty queryset and bail out
        # (queryset needed for django paginator)
        if not self.form.is_valid():
            return DigitizedWork.objects.none()

        solr_q = (
            ArchiveSearchQuerySet()
            .facet(*self.form.facet_fields)
            .order_by(self.form.get_solr_sort_field())
        )

        # components of query to filter digitized works
        if self.form.is_valid():
            search_opts = self.form.cleaned_data
            self.query = search_opts.get("query", None)
            collections = search_opts.get("collections", None)
            cluster_id = search_opts.get("cluster", None)

            solr_q.keyword_search(self.query)

            if cluster_id:
                # filter by group id if set
                solr_q = solr_q.within_cluster(cluster_id)

            # restrict by collection
            if collections:
                # if *all* collections are selected, there is no need to filter
                # (will return everything either way; keep the query simpler)
                if len(collections) < len(self.form.fields["collections"].choices):
                    # add quotes so solr will treat as exact phrase
                    # for multiword collection names
                    solr_q.work_filter(
                        collections_exact__in=['"%s"' % c for c in collections]
                    )

            # For collection exclusion logic to work properly, if no
            # collections are selected, no items should be returned.
            # This query should return no items but still provide facet
            # data to populate the collection filters on the form properly.
            else:
                solr_q.work_filter(collections_exact__exists=False)

            # filter books by title or author if there are search terms
            solr_q.work_title_search(search_opts.get("title", None))
            solr_q.work_filter(author=search_opts.get("author", None))

        for range_facet in self.form.range_facets:
            # range filter requested in search options
            start = end = None
            # if start or end is specified on the form, add a filter query
            if range_facet in search_opts and search_opts[range_facet]:
                start, end = search_opts[range_facet].split("-")
                # find works restricted by range
                solr_q.work_filter(**{"%s__range" % range_facet: (start, end)})

            # get minimum and maximum pub date values from the db
            pubmin, pubmax = self.form.pub_date_minmax()

            # NOTE: hard-coded values are fallback logic for when
            # no contents are in the database and pubmin/pubmax are None
            start = int(start) if start else pubmin or 0
            end = int(end) if end else pubmax or 1922

            # Configure range facet options specific to current field, to
            # support more than one range facet (even though not currently needed)
            # NOTE: per facet.range.include documentation, default behavior
            # is to include lower bound and exclude upper bound.
            # For simplicity, increase range end by one.
            # Calculate gap based start and end & desired number of slices
            # ideally, generate 24 slices; minimum gap size of 1
            # Use hardend to restrict last range to *actual* maximum value
            solr_q = solr_q.facet_range(
                range_facet,
                start=start,
                end=end + 1,
                gap=max(1, int((end - start) / 24)),
                hardend=True,
            )

        self.solrq = solr_q
        return solr_q

    def get_pages(self, solrq):
        """If there is a keyword search, query Solr for matching pages
        with text highlighting.
        NOTE: This has to be done as a separate query because Solr
        doesn't support highlighting on collapsed items."""

        if not self.query or not solrq.count():
            # if there is no keyword query, bail out
            return ({}, {})

        # work ids in solrq; quoting to handle ark ids
        work_id_l = ['"%s"' % d["id"] for d in solrq]

        # generate a list of page ids from the grouped results
        # NOTE: can't use alias for group_id because not using aliased queryset
        # (archive search queryset doesn't work properly for this query)
        solr_pageq = (
            PageSearchQuerySet()
            .filter(group_id__in=work_id_l)
            .filter(item_type="page")
            .search(content="(%s)" % self.query)
            .group("group_id", limit=2, sort="score desc")
            .highlight("content", snippets=3, method="unified")
        )

        # get response, this will be cached for rows specified
        # NOTE: rows argument is needed until this parasolr bug is fixed
        # https://github.com/Princeton-CDH/parasolr/issues/43
        response = solr_pageq.get_response(rows=100)

        # mimics structure of previous expand/collapse page results
        # dict is: group_id -> document list with page objects
        page_groups = {g["groupValue"]: g["doclist"] for g in response.groups}

        # get the page highlights from the solr response
        # dict is: pageid -> pagehighlights

ppa/archive/templates/archive/snippets/cluster_work.html
{# NOTE: expects cluster_id to be passed in #}
<div class="cluster-work icon container" >
    {# TODO: include count if we can easily get it ; search and browse x digitized works within cluster #}
    {# do NOT include any search parameters, to avoid unintentionally hiding cluster results #}
    <a href="{% url "archive:list" %}?cluster={{ cluster_id }}">search and browse within cluster</a>
</div>

ppa/archive/templates/archive/snippets/jump_top.html
<a title="back to top" class="ui icon basic button" href="#{{ anchor }}" id="jump-top">
    <i class="chevron up icon"></i>
</a>

ppa/archive/templates/archive/snippets/page_preview.html
{% comment %}
Page preview snippet displays page thumbnail and highlight text from
keyword search.  Used on both DigitizedWork list and detail views.

Expected context variables:
  - item_id: source id for the work the page belongs to
  - source: source name (e.g., HathiTrust, Gale, etc), for generating appropriate link
  - source_url: link to full record
  - image_url: image url (needed for Gale image urls)
  - page: page result with page.order attribute (page label/order, for determining thumbnail url)
  - highlights: dictionary of Solr highlighting results
{% endcomment %}
{% load ppa_tags %}
{% with page_link=source_url %}{# link to source url by default; override if page url is available #}
<div class="page">
  {% if source == 'HathiTrust' %}
    {% hathi_page_url item_id page.order as page_link %}
  {% elif source == 'Gale' %}
    {% gale_page_url source_url page.order as page_link %}
  {# currently no other sources with page level content, so no other case needed #}
  {% endif %}
    {% if source == 'HathiTrust' or source == 'Gale' %}  {# we currently only support page images for these two #}
    <div class="preview">
        <a href="{{ page_link }}"
          target="_blank" rel="noopener noreferrer">
          {% if source == 'HathiTrust' %}
          {% page_image_url item_id page.order 225 as 1x_img %}
          {% page_image_url item_id page.order 450 as 2x_img %}
          {# img with data-src/srcset attributes for lazy-loading  #}
          <img data-src="{{ 1x_img }}" data-srcset="{{ 1x_img}}, {{ 2x_img }} 2x"
              alt="page {{ page.label }}"/>
          <noscript>
            {# noscript image for fallback when javascript is disabled #}
            <img src="{{ 1x_img }}" srcset="{{ 1x_img}}, {{ 2x_img }} 2x"
              alt="page {{ page.label }}"/>
          </noscript>
          {% elif source == 'Gale' %}
          {# NOTE: may want to move to a template tag at some point #}
          {% with 2x_img=""|add:image_url|add:"?format=png&boundbox=725+450" 1x_img=""|add:image_url|add:"?format=png&boundbox=225+350" %}
          <img src="{{ 1x_img }}" srcset="{{ 1x_img}}, {{ 2x_img }} 2x"
              alt="page {{ page.label }}"/>
          {% endwith %}
          {% else %}
          {% endif %}
        </a>
    </div>
    {% endif %}
    {% if page.title %}<a>p. {{ page.title }}</a>{% endif %}
    <div class="snippets">
          <p class="page-number">
            <a href="{{ page_link }}" target="_blank" rel="noopener noreferrer">
              p. {{ page.label }}
            </a>
          </p>
        {% for snippet in highlights.content %}
        <p class="snippet">{{ snippet|solr_highlight }}</p>
        {% endfor %}
    </div>
</div>
{% endwith %}

ppa/archive/templates/archive/snippets/pagination.html
{% spaceless %}
<div class="items-per-page">
    <label class="display-label">Display</label>
    <a class="ui active basic button">{{ page_obj.paginator.per_page }}</a>
    <label class="results-label">Results</label>
</div>
<div class="page-controls">
        {# previous link at first (disabled if no previous)  #}
        {% if page_obj.has_previous %}
        <a name="previous page" title="previous page" rel="prev" class="ui icon basic button" href="?{% querystring_replace page=page_obj.previous_page_number %}">
            <i class="chevron left icon"></i>
        </a>
        {% else %}
        <a name="previous page" title="previous page" class="ui disabled icon basic button">
            <i class="chevron left icon"></i>
        </a>
        {% endif %}

        {% for number in page_obj.paginator.page_range %}

            {#  always display current page, marked as active #}
            {% if number == page_obj.number %}
                <a title="page {{number}}" class="ui active basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>

            {# for current page 1 or 2, display first 5 #}
            {% elif page_obj.number <= 2  and number <= 5 %}
                <a title="page {{number}}" class="ui basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>

            {# for current page last or next to last, display last 5 pages #}
            {% elif page_obj.number|add:1 >= page_obj.paginator.num_pages and number >= page_obj.paginator.num_pages|add:-4 %}
                <a title="page {{number}}" class="ui basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>

            {# display the two numbers before and after the current page #}
            {% elif page_obj.number|add:2 >= number and page_obj.number|add:-2 <= number %}
                <a title="page {{number}}" class="ui basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>

            {# always display the first page (not current page) #}
            {% elif forloop.first %}
                <a title="page {{number}}" class="ui basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>
                {# if there is a gap between 1 and group around current page #}
                {% if page_obj.number > 4 and page_obj.paginator.num_pages > 6 %}
                <span>...</span>
                {% endif %}

            {# always display last page (not current, not around current page) #}
            {% elif forloop.last %}
                {# indicate if there is a gap between current and last #}
                {% if page_obj.number|add:3 < number and number > 6 %}
                <span>...</span>
                {% endif %}
                <a title="page {{number}}" class="ui basic button" href="?{% querystring_replace page=number %}">{{ number }}</a>
            {% endif%}
        {% endfor %}

        {# next link at end (disabled if no next)  #}
        {% if page_obj.has_next %}
        <a name="next page" title="next page" rel="next" class="ui icon basic button" href="?{% querystring_replace page=page_obj.next_page_number %}">
            <i class="chevron right icon"></i>
        </a>
        {% else %}
        <a name="next page" title="next page" class="ui disabled icon basic button">
            <i class="chevron right icon"></i>
        </a>
        {% endif %}
</div>
{% endspaceless %}

ppa/archive/templates/archive/snippets/results_list.html
{% load static humanize ppa_tags %}
{% comment %}
this template can be rendered by digitizedwork_list.html or requested separately
via ajax, e.g. to update the search results.
{% endcomment %}
<div class="data">
    <pre class="count">
        Displaying {{ paginator.count|intcomma }} digitized work{{ paginator.count|pluralize }}
    </pre>
    {{ facet_ranges.pub_date|json_script:"facets" }}
</div>
<ol class="results-list">
    {% for item in object_list %}
        {% include 'archive/snippets/search_result.html' %}
    {% empty %}
        <div class="ui error message container">
            <p>{% firstof error "No matching works." %}</p>
        </div>
    {% endfor %}
</ol>
<div class="pagination-bottom ui container">
    {% include 'archive/snippets/pagination.html' %}
</div>

ppa/archive/templates/archive/snippets/results_within_list.html
{% load ppa_tags %}
{% comment %}
    This partial is rendered as part of `digitizedwork_detail.html` and can also
    be requested asynchronously to repopulate the search results.
{% endcomment %}
{% if query or page_highlights %}
    {% if not error %}
    <div class="occurrences ui center aligned text container">
        <p>{{ current_results.paginator.count }} occurrence{{ current_results.paginator.count|pluralize }}</p>
    </div>
    <div class="pagination ui container">
        {% include 'archive/snippets/pagination.html' with page_obj=current_results %}
    </div>
    {% endif %}
    <div class="results-list ui container">
        {% for page in current_results.object_list %}
            {% with highlights=page_highlights|dict_item:page.id%}
            <div class="ui page item">
                <div class="pages ui twelve wide column">
                    <div class="wrapper">
                        {% include 'archive/snippets/page_preview.html' with item_id=page.source_id  source=object.get_source_display source_url=object.source_url image_url=page.image_url %}
                    </div>
                </div>
            </div>
            {% endwith %}
        {% empty %}
            <div class="ui error message container">
                {# display error if something went wrong (bad query, etc.) #}
                <p>{% firstof error "No matching pages." %}</p>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% if not error and current_results.paginator.count > 5 %}
<div class="pagination ui container">
    {% include 'archive/snippets/pagination.html' with page_obj=current_results %}
</div>
{% endif %}

ppa/archive/templates/archive/snippets/search_result.html
{% load static humanize %}

<li class="item {{ item.work_type }}">
    {% if item.work_type == "full-work" %} {# unapi metadata only available for full works #}
    <abbr class="unapi-id" title="{{ item.group_id }}" aria-hidden="true"></abbr>
    {% endif %}

    <a href="{% if item.first_page %}{% url 'archive:detail' source_id=item.source_id start_page=item.first_page %}{% else %}{% url 'archive:detail' item.source_id %}{% endif %}{% if query %}?query={{ query }}{% endif %}" class="detail">
        <div class="brief-result container">
            <div class="title column">
                <div class="labels">
                    {% if page_obj %}
                        <p class="result-number">{{ page_obj.start_index|add:forloop.counter0 }}</p>
                    {% endif %}
                    {% if item.work_type != "full-work" %}
                    <div class="work-type icon" aria-label="{{ item.work_type }}"></div>
                    {% endif %}
                </div>
                <p>
                    {% spaceless %}
                    <span class="ui header">{{ item.title }}</span>
                    {% if item.work_type != "full-work" and item.book_journal %}
                    <span class="ui sub header book-journal">{{ item.book_journal }}</span>
                    {% else %}
                    <span class="ui sub header">{{ item.subtitle}}</span>
                    {% endif %}
                    {% endspaceless %}
                </p>
            </div>
            <div class="metadata column">
                <dl class="grid">
                    {% if item.author %}
                    <div class="author">
                        <dt>Author</dt>
                        <dd>{{ item.author }}</dd>
                    </div>
                    {% endif %}
                    {% if item.pub_date %}
                    <div class="pub-date">
                        <dt>Publication Date</dt>
                        <dd>{{ item.pub_date }}</dd>
                    </div>
                    {% endif %}
                    {% if item.publisher %}
                    <div class="publisher">
                        <dt>Publisher</dt>
                        <dd>{{ item.publisher }}</dd>
                    </div>
                    {% endif %}
                    {% if item.enumcron %}
                    <div class="volume">
                        <dt>Volume</dt>
                        <dd>{{ item.enumcron }}</dd>
                    </div>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <div class="score">
                        <dt>Relevance</dt>
                        <dd>{{ item.score }}</dd>
                        {% if page_groups and page_highlights %}
                            {% with results=page_groups|dict_item:item.id %}
                            <dt>Max relevance</dt>
                            <dd>{{ results.maxScore }}</dd>
                        {% endwith %}
                        {% endif %}
                    </div>
                    {% endif %}
                </dl>
                <div class="buttons">
                    {% if item.pk %} {# database object with many-to-many #}
                        {% for collection in item.collections.all %}
                            <label class="ui basic button">{{ collection }}</label>
                        {% endfor %}
                    {% else %} {# solr object with list of strings #}
                        {% for collection in item.collections %}
                            {# Don't display collection badge for uncategorized items #}
                            {% if collection != NO_COLLECTION_LABEL %}
                            <label class="ui basic button">{{ collection }}</label>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <div class="item-detail">
                        <span>See more details</span>
                        {% include 'snippets/chevron.svg' %}
                    </div>
                </div>

            </div>
        </div>
    </a>
    {# if the cluster id is set and differs from item id, work is part of a cluster #}
    {# only display when not searching within a cluster  #}
    {% if not search_form.cluster.value and item.cluster_id and item.cluster_id != item.id %}
        {% include "archive/snippets/cluster_work.html" with cluster_id=item.cluster_id %}
    {% endif %}
    <div class="page-previews container">
        {% if page_groups and page_highlights %}
        {% with results=page_groups|dict_item:item.id %}
            {% if results.numFound > 2 %}
            <span class="total-pages">
                {{ results.numFound|intcomma }} matching page{{ results.numFound|pluralize }}
            </span>
            {% endif %}
            <div class="pages">
                {% if page_highlights %}
                <div class="wrapper">
                    {% for page in results.docs %}
                    {% with highlights=page_highlights|dict_item:page.id %}
                        {% include 'archive/snippets/page_preview.html' with item_id=item.source_id source=item.source  source_url=item.source_url image_url=page.image_url %}
                    {% endwith %}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        {% endwith %}
        {% endif %}
    </div>
</li>

ppa/archive/templates/archive/snippets/sort.html
{% load static %}

<div class="sort">
    <label for="sort">Sort By</label>
    <div class="ui selection dropdown" id="sort">
        <img class="chevron icon"
            src="{% static 'img/icons/RightChevron.svg' %}" alt="">
        <input type="hidden" name="sort" id="{{ search_form.sort.id_for_label }}">
        <div class="text">
        {% for sort in search_form.sort %}
            {% if sort.data.selected %}
                {{ sort.choice_label }}
            {% endif %}
        {% endfor %}
        </div>
        <div class="menu">
            {% for sort in search_form.sort %}
            <div class="item{% if sort.data.selected %} active{% endif %} {{ sort.data.attrs.disabled }}"
                data-value="{{ sort.data.value }}">
                {{ sort.choice_label }}
            </div>
            {% endfor %}
        </div>
    </div>
    <noscript>{{ search_form.sort }}</noscript>
</div>