ppa/archive/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, re_path

from ppa.archive import views

app_name = "ppa.archive"

urlpatterns = [
    path(
        "add-to-collection/",
        staff_member_required(views.AddToCollection.as_view()),
        name="add-to-collection",
    ),
    path(
        "opensearch-description/",
        views.OpenSearchDescriptionView.as_view(),
        name="opensearch-description",
    ),
    re_path(
        r"^record/(?P<record_id>\d+)/",
        views.DigitizedWorkByRecordId.as_view(),
        name="record-id",
    ),
    # excerpt original page may be numeric or alpha (e.g., roman numerals)
    re_path(
        r"^(?P<source_id>[^-]+)-p(?P<start_page>[\da-zA-Z]+)/",
        views.DigitizedWorkDetailView.as_view(),
        name="detail",
    ),
    re_path(
        r"^(?P<source_id>[^-]+)/",
        views.DigitizedWorkDetailView.as_view(),
        name="detail",
    ),
    path("", views.DigitizedWorkListView.as_view(), name="list"),
]

ppa/urls.py
"""PPA URL Configuration

"""
from django.conf import settings
from django.conf.urls.static import serve
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView, TemplateView
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps import Sitemap
from wagtail.contrib.sitemaps import views as sitemap_views
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from ppa.archive.sitemaps import ArchiveViewsSitemap, DigitizedWorkSitemap
from ppa.unapi.views import UnAPIView

# sitemap configuration for sections of the site
sitemaps = {
    "pages": Sitemap,  # wagtail content pages
    "archive": ArchiveViewsSitemap,
    "digitizedworks": DigitizedWorkSitemap,
}


urlpatterns = [
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    re_path(
        r"^favicon\.ico$",
        RedirectView.as_view(url="/static/favicon.ico", permanent=True),
    ),
    path("admin/", admin.site.urls),
    # pucas urls for CAS login
    path("accounts/", include("pucas.cas_urls")),
    path("archive/", include("ppa.archive.urls", namespace="archive")),
    # unapi service endpoint for Zotero
    path("unapi/", UnAPIView.as_view(), name="unapi"),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # sitemaps
    re_path(
        r"^sitemap\.xml$",
        sitemap_views.index,
        {"sitemaps": sitemaps},
        name="sitemap-index",
    ),
    re_path(
        r"^sitemap-(?P<section>.+)\.xml$",
        sitemap_views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", include(wagtail_urls)),
]

# serve media content for development
if settings.DEBUG:
    urlpatterns = [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    ] + urlpatterns

    try:
        # include debug toolbar when available
        import debug_toolbar

        urlpatterns = [
            # include debug toolbar urls first to avoid getting caught by other urls
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

templates/snippets/about.html
{% load static %}

<div class="about ui simple item dropdown{% if active == 'about' %} triangle{% endif %}">
    <div class="text">About</div>
    <img class="dropdown icon" src="{% static 'img/icons/RightChevron.svg' %}" alt="">
    <div class="menu submenu">
        {# NOTE: currently relies on editorial not having show_in_menu set #}
        {% for page in request.site.root_page.get_children.live.in_menu %}
        <div class="item"><a href="{{ page.url }}">{{ page.title }}</a></div>
        {% endfor %}
    </div>
</div>

templates/snippets/analytics.html
{% load static %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GTAGS_ANALYTICS_ID }}"></script>
<script nonce="{{ request.csp_nonce }}">
    /*
      Google Analytics gtags snippet to be included if analytics are enabled.
    */
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{ GTAGS_ANALYTICS_ID }}');

</script>

templates/snippets/footer.html
{% load static wagtailcore_tags %}
<footer class="ui basic inverted segment centered grid" id="footer">
    <div class="ui container">
        <nav class="ui inverted borderless menu">
            <a class="item" href="{% slugurl 'home' %}">Home</a>
            <a class="item" href="{% slugurl 'editorial' %}">Editorial</a>
            <a class="item" href="{% slugurl 'collections' %}">Collections</a>
            <a class="item" href="{% url 'archive:list' %}">Archive</a>
        </nav>
        <div class="ui inverted horizontal link list">
            {% for page in request.site.root_page.get_children.live.in_menu %}
            <a class="item" href="{{ page.url }}">{{ page.title }}</a>
            {% endfor %}
        </div>
        <img class="ppa-logo" src="{% static 'img/logos/filled/logo-filled-monochrome.svg' %}" alt="Princeton Prosody Archive" />
        <div class="ui inverted horizontal list">
            <a class="item ui small image" href="https://www.princeton.edu/">
                <img src="{% static 'img/logos/pu-logo.svg' %}" alt="Princeton University" />
            </a>
            <a class="item ui tiny image" href="https://cdh.princeton.edu/">
                <img src="{% static 'img/logos/cdh-logo.svg' %}" alt="The Center for Digital Humanities at Princeton" />
            </a>
        </div>
        <div class="media">
            <div class="left">
                <a class="license" href="https://creativecommons.org/licenses/by/4.0/">
                    <img src="{% static 'img/logos/cc-by.svg' %}" alt="content licensed under Creative Commons CC-BY">
                </a>
                <span class="issn">ISSN: 2769-3619</span>
            </div>
            <div class="right">
                <a href="https://www.facebook.com/ProsodyArchive/">
                    <img src="{% static 'img/icons/facebook.svg' %}" alt="ProsodyArchive on Facebook"/>
                </a>
                <a href="https://twitter.com/ProsodyArchive">
                    <img src="{% static 'img/icons/twitter.svg' %}" alt="ProsodyArchive on Twitter"/>
                </a>
                <a href="https://www.instagram.com/prosodyarchive/">
                    <img src="{% static 'img/icons/instagram.svg' %}" alt="ProsodyArchive on  Instagram"/>
                </a>
            </div>
        </div>
        <div class="contact ui inverted horizontal link list">
            <span class="item">&copy; {% now 'Y' %} Trustees of Princeton University</span>
            <a class="item" href="https://accessibility.princeton.edu/accessibility-assistance">Accessibility Assistance</a>

            {# link to technical documentation page, if it exists #}
            {% slugurl 'technical' as technical_url %}
            {% if technical_url %}
            <a class="item" href="{{ technical_url }}">Technical</a>
            {% endif %}

            <span class="item" id="sw_version">v. {{ SW_VERSION }}</span>
        </div>
    </div>
</footer>

templates/snippets/head_meta.html
{% load fullurl %}
{% comment %}
Add HTML metadata tags for unfurling, twitter preview, etc.
Uses wagtail page fields if available; uses meta_page_title,
page_description, and page_meta_image if set in context.
{% endcomment %}
{% firstof page.seo_title page.title page_title as meta_page_title %}
{% firstof page.get_plaintext_description page.search_description page_description as meta_description %}

{# keywords for meta not yet implemented in wagtail #}
{# <meta name="keywords" content="{% block meta_keywords %}{% endblock %}"> #}
<meta name="description" content="{{ meta_description }}">

{# open graph metadata #}
<meta property="og:title" content="{{ meta_page_title }}" />
<meta property="og:type" content="website" />
<meta property="og:description" content="{{ meta_description }}"/>
<meta property="og:site_name" content="Princeton Prosody Archive"/>
{# twitter card #}
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="{{ meta_page_title }}"/>
<meta name="twitter:description" content="{{ meta_description }}" />
<meta name="twitter:site" content="@ProsodyArchive" />

{% if request %} {# full urls required for image, dependent on request in context #}
{% with default_image="img/logos/social.png" %}
{% firstof page_meta_image default_image as preview_image %}
<meta property="og:image" content="{% fullstatic preview_image %}" />
<meta name="twitter:image" content="{% fullstatic preview_image %}" />
{% endwith %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta name="twitter:url" content="{{ request.build_absolute_uri }}" />
<meta name="twitter:domain" content="{{ request.get_host }}" />
{% endif %}

templates/snippets/header.html
<header class="{{ style }}" id="header">
    <div class="banner"></div>
    <div class="lower"></div>
</header>

templates/snippets/nav.html
{% load static wagtailcore_tags %}

<!-- mobile navigation -->
<nav class="ui top sidebar vertical borderless menu {{ style }}" id="mobile-nav">
    {% include 'snippets/about.html' %}
    <a class="item" href="{% slugurl 'editorial' %}">Editorial</a>
    <a class="item" href="{% slugurl 'collections'%}">Collections</a>
    <a class="item" href="{% url 'archive:list' %}">
        Archive
        <img class="search icon"
            src="{% static 'img/icons/Search.svg' %}" alt="">
    </a>
</nav>

<!-- main navigation -->
<nav class="ui top fixed borderless menu {{ style }}" id="main-nav">
    <a class="toc item" id="toc">
        <img class="menu icon" src="{% static 'img/icons/Menu.svg' %}"
            alt="open menu">
        <img class="close icon" src="{% static 'img/icons/Delete.svg' %}"
            alt="close menu">
    </a>
    {% include 'snippets/about.html' %}
    <a href="{% slugurl 'editorial' %}"
        class="editorial item{% if active == 'editorial' %} active{% endif %}">
        Editorial
    </a>
    <div class="ui header brand">
        <a class="item" href="{% slugurl 'home' %}">
            <img src="{% static 'img/logotype/logotype.svg' %}" alt="home">
        </a>
    </div>
    <div class="right menu">
        <a class="collections item{% if active == 'collections' %} active{% endif %}"
            href="{% slugurl 'collections' %}">Collections
        </a>
        <a class="archive item{% if active == 'archive' %} active{% endif %}"
            href="{% url 'archive:list' %}">
            Archive
            <img class="search icon"
                src="{% static 'img/icons/Search.svg' %}" alt="">
        </a>
        <a class="search item" href="{% url 'archive:list' %}">
            <img class="search icon"
                src="{% static 'img/icons/Search.svg' %}" alt="search">
        </a>
    </div>
</nav>

templates/snippets/plausible_analytics.html
{% if INCLUDE_ANALYTICS and PLAUSIBLE_ANALYTICS_SCRIPT %}
{# plausible analytics #}
<script defer data-domain="prosody.princeton.edu" src="{{ PLAUSIBLE_ANALYTICS_SCRIPT }} "></script>
{% if PLAUSIBLE_ANALYTICS_404s %}
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>
{% endif %}
{% endif %}

templates/snippets/test_banner.html
{% if SHOW_TEST_WARNING %}
<div class="ribbon-box fade">
  <div class="ribbon-wrapper">
    <div class="ribbon"><h2>This is a <b>TEST</b> site</h2>
    <p>Content may change or be removed without warning</p>
    <button>OK</button>
    </div>
  </div>
</div>
{% endif %}